export const TECH_WORDS = [
  'javascript',
  'typescript',
  'python',
  'database',
  'frontend',
  'backend',
  'algorithm',
  'recursion',
  'framework',
  'component',
  'variable',
  'function',
  'interface',
  'container',
  'kubernetes',
  'devops',
  'refactor',
  'compiler',
  'runtime',
  'async',
  'promise',
  'callback',
  'closure',
  'prototype',
  'singleton',
  'observer',
  'iterator',
  'generator',
  'middleware',
  'endpoint',
  'payload',
  'repository',
  'deployment',
  'pipeline',
  'migration',
  'webhook',
  'socket',
  'protocol',
  'encryption',
  'authentication',
];

export function getRandomWord(): string {
  return TECH_WORDS[Math.floor(Math.random() * TECH_WORDS.length)];
}
